### ISSUE TITLE
Automatic tests and coding standard

### ISSUE THREAD

**Issue by janbarasek** [joserick/PNGMetadata#2]
I think this package should use automated tests with coding standard and PhpStan.

If you want I can send pull request.

Thanks.

**Comment by joserick** [comment]
@janbarasek That would be cool and at the same time learn something new.
Yes, send the pull request.

**Comment by janbarasek** [comment]
@joserick Done #3

**Comment by joserick** [comment]
@janbarasek I have added some questions to the pull request #3 but I also wanted to ask you if you have any links or tutorials that you recommend to me to learn PhpStan in depth and "automated tests" since I saw that you added a folder called "workflows" to the repository.

**Comment by janbarasek** [comment]
@joserick I've worked on most of the requests, you can merge it.

I recommend official documentation for studying PhpStan: https://phpstan.org

Alternatively, we can arrange an online meeting and I help you resolve specific situations.

**Comment by joserick** [comment]
@janbarasek Thanks for answering my question in the pull request and for making the changes, it looks great, also thanks for the link. I'll give it a good read.
