### ISSUE TITLE
Codereview

### ISSUE THREAD

**Issue by janbarasek** [joserick/PNGMetadata#5]
Hello @joserick,

I saw your last commit (https://github.com/joserick/PNGMetadata/commit/1f277010aeb61458efdff21484c6dd9135d5231a). I have a number of reservations about it because it violates some best practices.

I suggest that we can develop new features in the branches and I will always do a coder review within the pull request.

I added notes directly to the commit on what should be fixed. Some errors can occur repeatedly, I have marked each error only once.

Thanks.

**Comment by joserick** [comment]
Hello @janbarasek 

I have made the changes based on your comments in [1f27701](https://github.com/joserick/PNGMetadata/commit/1f277010aeb61458efdff21484c6dd9135d5231a) but have responded in some of these comments with questions.

In the same way I have created the branch for development as you suggested. [develop](https://github.com/joserick/PNGMetadata/tree/develop)

Thanks.

**Comment by janbarasek** [comment]
Thank you very much. I responded to all comments where needed.
