### ISSUE TITLE
Fuzzing?

### ISSUE THREAD

**Issue by decrypted** [joserick/PNGMetadata#6]
Hi,

did you already do some fuzzing against this?

https://github.com/joserick/PNGMetadata/blob/master/src/PNGMetadata.php#L375

has me worried. Nsize - the unsigned long could be the savior to not loop forever

ideas ? ;)

thx for the lib!

**Comment by decrypted** [comment]
First random find
end() expects parameter 1 to be array, int given

#0 /var/www/html/vendor/joserick/png-metadata/src/PNGMetadata.php(462): end(0)
#1 /var/www/html/vendor/joserick/png-metadata/src/PNGMetadata.php(103): PNGMetadata\PNGMetadata->extractRBG()

**Comment by janbarasek** [comment]
Hello @decrypted, can you send a Pull request, please? :)

**Comment by joserick** [comment]
Interesting, yes... @decrypted please send a pull, I want to learn about this.

**Comment by joserick** [comment]
Fixed in #8
